=== lucaschimweg/dhbw-teamplanner/frontend/dtd/management.dtd
<!ELEMENT overview (team, jobDefinition)>
<!ELEMENT team (description?, memberDefinition+)>
<!ATTLIST team
        name CDATA #REQUIRED >

<!ELEMENT description (#PCDATA) >

<!ELEMENT memberDefinition EMPTY>
<!ATTLIST memberDefinition
        id ID #REQUIRED
        you (true|false) "false"
        leader (true|false) "false"
        startTime CDATA #IMPLIED
        endTime CDATA #IMPLIED
        name CDATA #IMPLIED>

<!ELEMENT member EMPTY>
<!ATTLIST member
        id IDREF #REQUIRED >

<!ELEMENT teamOverview (team, jobDefinition*)>

<!ELEMENT jobDefinition (description?, member+, dependsOn+)>
<!ATTLIST jobDefinition
        name CDATA #REQUIRED
        id ID #REQUIRED
        planned (true|false) #REQUIRED>

<!ELEMENT dependsOn EMPTY>
<!ATTLIST dependsOn
        id IDREF #REQUIRED>

=== lucaschimweg/dhbw-teamplanner/frontend/test/manage.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://localhost/xslt/manage.xsl"?>
<!DOCTYPE overview SYSTEM "/dtd/management.dtd">

<overview xmlns="/dtd/management.dtd">
    <team name="TP Development Team IV">
        <description>Das hier ist ein Supergeiles Team! Yeah!</description>
        <memberDefinition id="u1" name="Luca Schimweg" leader="true"/>
        <memberDefinition id="u4" name="Hendrik Leier" you="true" startTime="08:00" endTime="18:00"/>
    </team>

    <jobDefinition name="Kickoff 1" id="0" planned="true">
        <member id="u1"/>
        <member id="u4"/>
    </jobDefinition>

    <jobDefinition name="Kickoff 2" id="1" planned="true">
        <member id="u1"/>
        <member id="u4"/>
        <dependsOn id="0"/>
    </jobDefinition>

    <jobDefinition name="Kickoff 3" id="2" planned="true">
        <member id="u1"/>
        <member id="u4"/>
        <dependsOn id="0"/>
        <dependsOn id="1"/>
    </jobDefinition>

    <jobDefinition name="Kickoff 4" id="3" planned="true">
        <member id="u1"/>
        <member id="u4"/>
        <dependsOn id="1"/>
        <dependsOn id="0"/>
        <dependsOn id="2"/>
    </jobDefinition>

    <jobDefinition name="Kickoff 5" id="5" planned="true">
        <member id="u1"/>
        <member id="u4"/>
    </jobDefinition>

    <jobDefinition name="Kickoff 6" id="6" planned="true">
        <member id="u1"/>
        <member id="u4"/>

        <dependsOn id="5"/>
        <dependsOn id="2"/>
        <dependsOn id="1"/>
    </jobDefinition>

    <jobDefinition name="Kickoff 7" id="7" planned="true">
        <member id="u1"/>
        <member id="u4"/>

        <dependsOn id="2"/>
    </jobDefinition>

    <jobDefinition name="Kickoff 8" id="8" planned="false">
        <member id="u1"/>
        <member id="u4"/>
    </jobDefinition>

    <jobDefinition name="Kickoff 9" id="9" planned="false">
        <member id="u1"/>
        <member id="u4"/>
    </jobDefinition>

</overview>
