=== lucaschimweg/dhbw-teamplanner/frontend/dtd/teamplanner.dtd
<!ELEMENT week (team, day+)>
<!ATTLIST week
    offset CDATA #REQUIRED >

<!ELEMENT team (description?, memberDefinition+)>
<!ATTLIST team
    name CDATA #REQUIRED >

<!ELEMENT description (#PCDATA) >

<!ELEMENT memberDefinition EMPTY>
<!ATTLIST memberDefinition
        id ID #REQUIRED
        you (true|false) "false"
        leader (true|false) "false"
        startTime CDATA #IMPLIED
        endTime CDATA #IMPLIED
        name CDATA #IMPLIED>

<!ELEMENT day (job*, jobContinuation*)>
<!ATTLIST day
        today (true|false) "false"
        date CDATA #REQUIRED >

<!ELEMENT job (description?, member+)>
<!ATTLIST job
        timeFrom CDATA #REQUIRED
        timeTo CDATA #REQUIRED
        name CDATA #REQUIRED
        duration CDATA #REQUIRED
        id ID #REQUIRED >

<!ELEMENT jobContinuation EMPTY>
<!ATTLIST jobContinuation
        timeFrom CDATA #REQUIRED
        timeTo CDATA #REQUIRED
        job IDREF #REQUIRED >

<!ELEMENT member EMPTY>
<!ATTLIST member
        id IDREF #REQUIRED >

<!ELEMENT teamOverview (team, jobDefinition*)>

<!ELEMENT jobDefinition (description?, member+, dependsOn+)>
<!ATTLIST jobDefinition
        name CDATA #REQUIRED
        id ID #REQUIRED
        duration CDATA #REQUIRED
        planned (true|false) #IMPLIED
        editing (true|false) #IMPLIED>

<!ELEMENT dependsOn EMPTY>
<!ATTLIST dependsOn
        id IDREF #REQUIRED>

=== lucaschimweg/dhbw-teamplanner/frontend/test/team.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/xslt/team.xsl"?>
<!DOCTYPE teamOverview SYSTEM "https://planner.schimweg.net/dtd/teamplanner.dtd">
<teamOverview xmlns="https://planner.schimweg.net/dtd/teamplanner.dtd">
    <jobDefinition name="Projektbeginnbesprechung" duration="60" id="1">
        <description>Ein Kaffe und ab geht die Party!</description>
        <dependsOn id="14"/>
        <member id="u1"/>
        <member id="u4"/>
        <member id="u8"/>
        <member id="u18"/>
    </jobDefinition>
    <jobDefinition name="Implementationsphase Backend" duration="120" id="2">
        <description>Luca implementiert</description>
        <dependsOn id="1"/>
        <dependsOn id="3"/>
        <member id="u1"/>
        <member id="u4"/>
        <member id="u8"/>
    </jobDefinition>
    <jobDefinition name="Implementationsphase Frontend" duration="60" id="3">
        <description>Hendrik implementiert</description>
        <dependsOn id="1"/>
        <member id="u4"/>
    </jobDefinition>
    <jobDefinition name="Implementation zusammenführen" duration="60" id="4">
        <description>Kaffeee!!</description>
        <dependsOn id="1"/>
        <member id="u1"/>
        <member id="u4"/>
        <member id="u18"/>
    </jobDefinition>
    <jobDefinition name="QA Teamintern" duration="600" id="5">
        <dependsOn id="4"/>
        <member id="u1"/>
        <member id="u4"/>
        <member id="u8"/>
        <member id="u18"/>
    </jobDefinition>
    <jobDefinition name="QA 2 Teamextern" duration="360" id="6">
        <dependsOn id="5"/>
        <member id="u1"/>
        <member id="u4"/>
    </jobDefinition>
    <jobDefinition name="Gemeinsames Meeting" duration="120" id="7">
        <dependsOn id="6"/>
        <member id="u1"/>
        <member id="u4"/>
        <member id="u18"/>
    </jobDefinition>
    <jobDefinition name="Revision mit Kunden" duration="120" id="8">
        <dependsOn id="7"/>
        <member id="u1"/>
        <member id="u4"/>
    </jobDefinition>
    <jobDefinition name="Überarbeitung des Codes" duration="360" id="9">
        <dependsOn id="7"/>
        <member id="u1"/>
        <member id="u4"/>
    </jobDefinition>
    <jobDefinition name="QA 3" duration="240" id="10">
        <dependsOn id="9"/>
        <member id="u1"/>
        <member id="u4"/>
    </jobDefinition>
    <jobDefinition name="Erarbeitung Vortrag" duration="120" id="11">
        <dependsOn id="9"/>
        <dependsOn id="10"/>
        <member id="u1"/>
        <member id="u4"/>
    </jobDefinition>
    <jobDefinition name="Vortrag Intern" duration="120" id="12">
        <dependsOn id="11"/>
        <member id="u1"/>
        <member id="u4"/>
        <member id="u8"/>
    </jobDefinition>
    <jobDefinition name="Vortrag Extern" duration="120" id="13">
        <dependsOn id="12"/>
        <member id="u1"/>
        <member id="u4"/>
    </jobDefinition>
    <jobDefinition name="Kennenlernen" duration="60" id="14">
        <description>Wir wollen uns ja auch erstmal kennenlernen!</description>
        <dependsOn id="15"/>
        <member id="u1"/>
        <member id="u4"/>
        <member id="u8"/>
    </jobDefinition>
    <jobDefinition name="Gemeinsames Frühstück" duration="60" id="15">
        <description>Das hier ist ein supercooles Frühstück, ich freue mich schon wirklich darauf!&#xD;
            &#xD;
            Auf uns!&#xD;
            &#xD;
            &#xD;
            Gruß&#xD;
            Luca</description>
        <member id="u1"/>
        <member id="u4"/>
        <member id="u8"/>
        <member id="u18"/>
    </jobDefinition>
    <team name="TP Development Team IV">
        <description>Das hier ist ein Supergeiles Team! Yeah!</description>
        <memberDefinition id="u1" name="Luca Schimweg" leader="true" you="true" startTime="08:00" endTime="18:00"/>
        <memberDefinition id="u4" name="Hendrik Leier"/>
        <memberDefinition id="u8" name="Nico Diefenbacher"/>
        <memberDefinition id="u18" name="Jonas Heinrich"/>
        <memberDefinition id="u19" name="Zeno Berkhan"/>
    </team>
</teamOverview>

=== lucaschimweg/dhbw-teamplanner/common/examples/teamOverview.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE teamOverview SYSTEM "https://teamplanner.schimweg.net/teamplanner.dtd" >

<teamOverview xmlns="https://teamplanner.schimweg.net/teamplanner.dtd">
    <team name="Mein Team">
        <description>Das hier ist ein supercooles Team!</description>
        <memberDefinition leader="true" you="true" startTime="08:00" endTime="16:00" id="25" name="Luca Schimweg" />
        <memberDefinition id="26" name="Hendrik Leier" />
    </team>

    <jobDefinition name="Mein Superjob" duration="20" id="123">
        <member id="25"/>
    </jobDefinition>

    <jobDefinition name="Mein zweiter Job" duration="20" id="456">
        <description>Das hier ist ein Job</description>
        <dependsOn id="123" />
        <member id="25"/>
    </jobDefinition>
</teamOverview>

=== lucaschimweg/dhbw-teamplanner/common/examples/week.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE week SYSTEM "https://teamplanner.schimweg.net/teamplanner.dtd" >

<week xmlns="https://teamplanner.schimweg.net/teamplanner.dtd">
    <team name="Supergeiles Team">
        <description>Wir wollen etwas sehr cooles bauen!</description>
        <memberDefinition id="25" leader="true" name="Luca Schimweg" />
        <memberDefinition id="26" you="true" name="Hendrik Leier" />
        <memberDefinition id="27" name="Jonas Heinrich" />
    </team>

    <day date="2019-06-24">
        <job timeFrom="08:00" timeTo="09:30" duration="90" name="Das hier ist der Name" id="2501">
            <description>
                Hallo das hier ist eine Supergeile description!
            </description>
            <member id="25" />
            <member id="26" />
            <member id="27" />
        </job>
        <job timeFrom="09:30" timeTo="10:00" duration="30" name="Job ohne description!" id="2391">
            <member id="25" />
        </job>
        <job timeFrom="10:00" timeTo="18:00" duration="720" name="Job bis morgen" id="3210">
            <member id="25" />
            <member id="27" />
        </job>
    </day>

    <day date="2019-06-25">
        <jobContinuation timeFrom="08:00" timeTo="12:00" job="3210" />
    </day>

    <day date="2019-06-26">
        <job timeFrom="08:00" timeTo="09:10" name="Frühstück" duration="60" id="84219">
            <description>Brunch mit dem Team!</description>
            <member id="25"/>
            <member id="26"/>
        </job>
    </day>
</week>

=== lucaschimweg/dhbw-teamplanner/frontend/test/manageCreateJob.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://localhost/xslt/manageCreateJob.xsl"?>
<!DOCTYPE teamOverview SYSTEM "/dtd/teamplanner.dtd">

<teamOverview xmlns="/dtd/teamplanner.dtd">
    <team name="TP Development Team IV">
        <description>Das hier ist ein Supergeiles Team! Yeah!</description>
        <memberDefinition id="u1" name="Luca Schimweg"/>
        <memberDefinition id="u4" name="Hendrik Leier" you="true" leader="true" startTime="08:00" endTime="18:00"/>
        <memberDefinition id="u5" name="Jonas Heinrich" startTime="08:00" endTime="18:00"/>
        <memberDefinition id="u6" name="Zeno Berkan" startTime="08:00" endTime="18:00"/>
        <memberDefinition id="u7" name="Nico Diefenbacher" startTime="08:00" endTime="18:00"/>
    </team>

    <jobDefinition name="Kickoff 1" id="0" planned="true" duration="0">
        <member id="u1"/>
        <member id="u4"/>
    </jobDefinition>

    <jobDefinition name="Kickoff 2" id="1" planned="true" duration="0">
        <member id="u1"/>
        <member id="u4"/>
        <dependsOn id="0"/>
    </jobDefinition>

    <jobDefinition name="Kickoff 3" id="2" planned="true" duration="0">
        <member id="u1"/>
        <member id="u4"/>
        <dependsOn id="0"/>
        <dependsOn id="1"/>
    </jobDefinition>

    <jobDefinition name="Kickoff 4" id="3" planned="true" duration="0">
        <member id="u1"/>
        <member id="u4"/>
        <dependsOn id="1"/>
        <dependsOn id="0"/>
        <dependsOn id="2"/>
    </jobDefinition>

    <jobDefinition name="Kickoff 5" id="5" planned="true" duration="0">
        <member id="u1"/>
        <member id="u4"/>
    </jobDefinition>

    <jobDefinition name="Kickoff 6" id="6" editing="true" planned="true" duration="0">
        <member id="u1"/>
        <member id="u7"/>
        <member id="u4"/>

        <dependsOn id="5"/>
        <dependsOn id="2"/>
        <dependsOn id="1"/>
    </jobDefinition>

    <jobDefinition name="Kickoff 7" id="7" planned="true" duration="0">
        <member id="u1"/>
        <member id="u4"/>

        <dependsOn id="2"/>
    </jobDefinition>

    <jobDefinition name="Kickoff 8" id="8" planned="false" duration="0">
        <member id="u1"/>
        <member id="u4"/>
    </jobDefinition>

    <jobDefinition name="Kickoff 9" id="9" planned="false" duration="0">
        <member id="u1"/>
        <member id="u4"/>
        <member id="u5"/>
        <member id="u6"/>
        <member id="u7"/>
    </jobDefinition>

</teamOverview>
